#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx 
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
