#!/usr/bin/env bash
# a script that print based on trap
echo "$BASHPID">/var/run/myscript.pid
while :
do
echo "To infinity and beyond"
trap "echo I hate the kill command; rm /var/run/myscript.pid" SIGTERM
trap "rm /var/run/myscript.pid" SIGQUIT
trap "echo Y U no love me?!" SIGINT
done
