#!/usr/bin/env bash
# a script that display history of  etc/passwd 
FILENAME="/etc/passwd"
i=0
while IFS=: read -r name x id n run mor no ;
do
  echo "The user $name is part of $id gang, lives in $mor and rides $no. $id's place is protected by the passcode $x, more info about the user here: $name"
if [ $i -eq 1 ];then
	echo "$n, $run"

fi
done < $FILENAME

