#!/usr/bin/env bash
# a script that print hi if 9 else Best school.
i=0
while [ $i -le 10 ]
do
	if [ $i == 9 ];then
	echo "Hi"
	else
	echo "Best School"
	fi
	if [ $i == 4 ];then
	echo "$i"
	fi
	((i++))
done

