#!/usr/bin/env bash
# a script that display  a clock.
hour=0
i=1
echo "Hour: $hour"
while [ $hour -le 12 ]
do
	while [ $i -le 60 ]
	do
	if [ $i == 60 ];then
		i=1
		hour=$((hour + 1))
		if [ $hour -eq 13 ];then
			exit
		else
			echo "Hour: $hour"
		fi
	elif [ $hour -eq 13 ]
	then
	     exit  
     else
	    echo "$i"
	((i++))
	fi
done
done
