#!/usr/bin/env bash
# a script that display  a clock.
hour=0
i=1
echo "Hour: $hour"
while [ $hour -le 12 ]
do
	while [ $i -le 60 ]
	do
	echo "$i"
	if [ $i == 59 ];then
		i=0
		hour=$((hour + 1))
		echo "Hour: $hour"
	elif [ $hour -eq 12 ]
	then
	     exit  
	fi
	((i++))
	done
done
