#!/usr/bin/env bash
#check a file
file_path="/alx-system_engineering-devops/0x04-loops_conditions_and_parsing"
if [ -e "$file_path" ]; then
    echo "school file exists"

    if [ -s "$file_path" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "$file_path" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
